version: "3.8"
services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
    nodeserver:
        depends_on:
            - mysqldb
        build:
            context: ./backend
        restart: always
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
          - HOST=mysqldb
          - USER=$MYSQLDB_USER
          - PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - DB=$MYSQLDB_DATABASE
          - DB_PORT=$MYSQLDB_DOCKER_PORT
          - NODE_ENV=$NODE_ENV
          - TOKEN_SECRET=$NODE_TOKEN_SECRET
        stdin_open: true
        tty: true
    nginx:
        image: nginx:latest
        depends_on:
            - mysqldb
            - nodeserver
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf/:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
    db: